### ISSUE TITLE
Group capstone: set up your Kanban board

### ISSUE THREAD

**Issue by nikoescobal** [nikoescobal/API-based-app#23]
- Add all cards and assignees
- Run script to connect automation
- We are two (2) people in the group
- https://github.com/nikoescobal/API-based-app/projects/1

**Comment by Dipeshtwis** [comment]
Hi @nikoescobal and @Tchilo, 

:+1: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


 ## Required Changes ♻️


- [ ] You have missed assigning one card to the partner. Please make sure to assign each card to the right person.

![Screenshot from 2021-10-11 23-46-40](https://user-images.githubusercontent.com/22434660/136836214-4c1d3167-2e16-410e-a832-3bffe5154549.png)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- N.A.

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**_Dipesh Kumar_**


------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project(check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
